### ISSUE TITLE
Save off nwm forecast as .csvs and include option to read from saved csvs

### ISSUE THREAD

**Issue by pclemins** [CIROH-UVM/forecast-workflow#15]
You can use the code for gfs as a template.

Use the same flag in AEM3D_prep to read (or not read) from the csvs.

**Comment by n-beckage** [comment]
Adding an option `save_csv` to `get_data()` for gfs and nwm. I'm thinking we can then create a general function, maybe
"`load_data()`", in `lib.py` that will load the data from each module, either from previously saved csv's or by aggregating the data series/frames directly from the raw data. That way if you want to do multiple runs on the same set of data, you can change a setting `use_csv` to `True`, which will make the module run much faster. 

For example, this code, which is currently in `AEM3D_prep_IAM.py`, could go into `load_data()`:
```python
    ############## Use this bit to load forecast climate from .csvs previously created above
    if gfs_csv:
        climateForecast = {}
        for zone in ['401', '402', '403']:
            climateForecast[zone] = pd.read_csv(
                        os.path.join(root_dir, f'forecastData/gfs/gfs.{forecastDate.strftime("%Y%m%d")}/gfs{zone}.csv'),
                        index_col='time',
                        parse_dates=True)
    ##############
    else:
    ############## Use this bit to load forecast climate from original GRIB files and create .csvs for quick loading later
        climateForecast = gfs_tools.get_data(
                gfs_dir=os.path.join(root_dir, f'forecastData/gfs/gfs.{forecastDate.strftime("%Y%m%d")}/00/atmos/'),
                location_dict={'401': (45.00, -73.25),
                               '402': (44.75, -73.25),
                               '403': (44.75, -73.25)})
        for zone in climateForecast.keys():
            climateForecast[zone] = climateForecast[zone].rename_axis('time').astype('float')
            climateForecast[zone].to_csv(os.path.join(root_dir, f'forecastData/gfs/gfs.{forecastDate.strftime("%Y%m%d")}/gfs{zone}.csv'))
    ##############
``` 

At minimum, I'm adding a `save_csv` flag to `nwm_forecast.get_data()` so that we can do the same as above for nwm data.
